default_stages:
  - commit
  - push

repos:
  - repo: https://github.com/ambv/black
    rev: '23.1.0'
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/pycqa/isort
    rev: '5.12.0'
    hooks:
      - id: isort

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest -s
        language: system
        types: [python]
        verbose: true

