{
 "title": "Kubernetes Kafka",
 "description": "Global Kafka dashboard running on Kubernetes. Support  Bitnami Kafka chart https://github.com/bitnami/charts/tree/master/bitnami/kafka ",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(kafka_controller_kafkacontroller_activecontrollercount_value, namespace)"
   },
   {
    "name": "broker",
    "query": "label_values(kafka_controller_kafkacontroller_activecontrollercount_value{namespace=\"$namespace\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{namespace=\"$namespace\", app_kubernetes_io_component=\"kafka\"}) / 3"
    }
   ]
  },
  {
   "title": "Number of brokers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_brokers{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Active controller status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount_value{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "In-sync replicas shrinks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "- sum(kafka_server_replicamanager_total_isrshrinkspersec_count{namespace=\"$namespace\", instance=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "Under replicated partitions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_under_replicated_partition{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Partition count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_total_partitioncount_value{namespace=\"$namespace\", instance=~\"$broker\"}"
    }
   ]
  },
  {
   "title": "Broker status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{namespace=\"$namespace\", instance=~\"$broker\"}"
    }
   ]
  },
  {
   "title": "Unclean leader election",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_controllerstats_uncleanleaderelectionspersec_count{namespace=\"$namespace\", instance=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "Active controller",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount_value{namespace=\"$namespace\"} == 1"
    }
   ]
  },
  {
   "title": "In-sync replicas expands",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "- sum(kafka_server_replicamanager_total_isrexpandspersec_count{namespace=\"$namespace\", instance=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "Offline partitions count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount_value{namespace=\"$namespace\", instance=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "Bytes rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_total_bytesinpersec_count{namespace=\"$namespace\", instance=~\"$broker\"} / kafka_server_brokertopicmetrics_total_bytesoutpersec_count{namespace=\"$namespace\", instance=~\"$broker\"}",
     "legendFormat": "Broker {{ instance }}"
    }
   ]
  },
  {
   "title": "Messages IN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_total_messagesinpersec_oneminuterate{namespace=\"$namespace\", instance=~\"$broker\"}",
     "legendFormat": "{{ instance }} {{ value }}"
    }
   ]
  },
  {
   "title": "Number of partitions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_total_partitioncount_value{namespace=\"$namespace\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Bytes IN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_total_bytesinpersec_count{namespace=\"$namespace\", instance=~\"$broker\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Bytes OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_total_bytesoutpersec_count{namespace=\"$namespace\", instance=~\"$broker\"}[5m])",
     "legendFormat": "Broker {{ instance }}"
    }
   ]
  },
  {
   "title": "In-sync replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "- kafka_server_replicamanager_total_isrshrinkspersec_count{namespace=\"$namespace\", instance=~\"$broker\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memory_heapmemoryusage_used{namespace=\"$namespace\", instance=~\"$broker\"}",
     "legendFormat": "used {{ instance }}"
    },
    {
     "expr": "java_lang_memory_heapmemoryusage_max{namespace=\"$namespace\", instance=~\"$broker\"}",
     "legendFormat": "max {{ instance }}"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemcpuload{namespace=\"$namespace\", instance=~\"$broker\"} * 100",
     "legendFormat": "system {{ instance }}"
    },
    {
     "expr": "java_lang_operatingsystem_processcpuload{namespace=\"$namespace\", instance=~\"$broker\"} * 100",
     "legendFormat": "process {{ instance }}"
    }
   ]
  },
  {
   "title": "System memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_operatingsystem_totalphysicalmemorysize{namespace=\"$namespace\", instance=~\"$broker\"}",
     "legendFormat": "Total memory {{ instance }}"
    },
    {
     "expr": "java_lang_operatingsystem_freephysicalmemorysize{namespace=\"$namespace\", instance=~\"$broker\"}",
     "legendFormat": "Free memory {{ instance }}"
    },
    {
     "expr": "java_lang_operatingsystem_totalswapspacesize{namespace=\"$namespace\", instance=~\"$broker\"}",
     "legendFormat": "Total SWAP  {{ instance }}"
    },
    {
     "expr": "java_lang_operatingsystem_freeswapspacesize{namespace=\"$namespace\", instance=~\"$broker\"}",
     "legendFormat": "Free SWAP  {{ instance }}"
    },
    {
     "expr": "java_lang_operatingsystem_committedvirtualmemorysize{namespace=\"$namespace\", instance=~\"$broker\"}",
     "legendFormat": "Committed virtual memory {{ instance }}"
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemloadaverage{namespace=\"$namespace\", instance=~\"$broker\"}",
     "legendFormat": "System load average"
    },
    {
     "expr": "java_lang_operatingsystem_availableprocessors{namespace=\"$namespace\", instance=~\"$broker\"}",
     "legendFormat": "Available Processors"
    }
   ]
  },
  {
   "title": "Open file descriptor",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_operatingsystem_openfiledescriptorcount{namespace=\"$namespace\", instance=~\"$broker\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(java_lang_operatingsystem_totalphysicalmemorysize{namespace=\"$namespace\", instance=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_classloading_loadedclasscount{namespace=\"$namespace\", instance=~\"$broker\"}",
     "legendFormat": "Loaded {{ instance }}"
    },
    {
     "expr": "java_lang_classloading_loadedclasscount_total{namespace=\"$namespace\", instance=~\"$broker\"}",
     "legendFormat": "Total loaded {{ instance }}"
    },
    {
     "expr": "java_lang_classloading_loadedclasscount_total{namespace=\"$namespace\", instance=~\"$broker\"}",
     "legendFormat": "Unloaded {{ instance }}"
    },
    {
     "expr": "delta(java_lang_classloading_loadedclasscount{namespace=\"$namespace\", instance=~\"$broker\"}[5m])",
     "legendFormat": "Delta {{ instance }}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_threading_threadcount{namespace=\"$namespace\", instance=~\"$broker\"}",
     "legendFormat": "Current {{ instance }}"
    },
    {
     "expr": "java_lang_threading_daemonthreadcount{namespace=\"$namespace\", instance=~\"$broker\"}",
     "legendFormat": "Daemon {{ instance }}"
    },
    {
     "expr": "java_lang_threading_peakthreadcount{namespace=\"$namespace\", instance=~\"$broker\"}",
     "legendFormat": "Peak {{ instance }}"
    },
    {
     "expr": "java_lang_threading_totalstartedthreadcount{namespace=\"$namespace\", instance=~\"$broker\"}",
     "legendFormat": "Started total {{ instance }}"
    }
   ]
  },
  {
   "title": "Total CPUs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(java_lang_operatingsystem_availableprocessors{namespace=\"$namespace\", instance=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_requestspersec_count{namespace=\"$namespace\", instance=~\"$broker\", request=~\"Produce, version=.*\"}",
     "legendFormat": "{{ instance }} produce"
    },
    {
     "expr": "kafka_network_requestmetrics_requestspersec_count{namespace=\"$namespace\", instance=~\"$broker\", request=~\"FetchConsumer, version=.*\"}",
     "legendFormat": "{{ instance }} fetch consumer"
    },
    {
     "expr": " kafka_network_requestmetrics_requestspersec_count{namespace=\"$namespace\", instance=~\"$broker\", request=~\"FetchFollower, version=.*\"}",
     "legendFormat": "{{ instance }} fetch follower"
    }
   ]
  },
  {
   "title": "Purgatory delayed fetch operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_delayedoperationpurgatory_numdelayedoperations_fetch_value{namespace=\"$namespace\", instance=~\"$broker\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Log size by broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_log_log_size{namespace=\"$namespace\"}) by(instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "All number of requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_network_requestmetrics_requestspersec_count{namespace=\"$namespace\", instance=~\"$broker\"}) by (request)",
     "legendFormat": "{{ request }}"
    }
   ]
  },
  {
   "title": "Idle network processors",
   "type": "graph",
   "description": "The average fraction of time the network processors are idle",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_processor_idlepercent_value{namespace=\"$namespace\", instance=~\"$broker\"}",
     "legendFormat": "{{ instance }} network processor {{ network_processor }}"
    }
   ]
  },
  {
   "title": "Idle request handler threads",
   "type": "graph",
   "description": "The average fraction of time the request handler threads are idle",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_kafkarequesthandlerpool_total_requesthandleravgidlepercent_oneminuterate{namespace=\"$namespace\", instance=~\"$broker\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}